### ISSUE TITLE
Conda with Python 3.9 breaks this

### ISSUE THREAD

**Issue by ajwlab** [ctboughter/AIMS#1]
I believe Conda with Python 3.9 breaks AIMS dependencies because of a new glibc version 2.3.1 that conflicts with the version 2.17 that is required by the dependencies of this project, which allows none of them to be installed.

Downgrading to Python 3.7 fixed the issue and I was able to run with Spyder 5

**Comment by ctboughter** [comment]
Thanks for bringing up this issue! If using Python 3.9 is critical for your work, I seem to have found a solution here. I will add, I haven't yet validated this solution for consistency, so I'll keep this issue open until I can do so.

I'll update this in the master branch later this week, but if you're running the GUI, remove "from Bio.Alphabet import IUPAC" from the top of aims_loader.py in the app subdirectory. The Jupyter notebooks should run fine without any edits. Then, try to create an environment with the following module versions (tested on a MacBook Pro with macOS version 10.15.7):

python=3.9.6

(I'll leave everything else with "conda install" for copy/paste potential)

 conda install -c conda-forge kivy=2.0.0
 conda install -c conda-forge biopython=1.79
 conda install -c conda-forge scipy=1.6.2
 conda install pandas=1.3.1
 conda install numpy=1.20.3
 conda install matplotlib=3.4.2
 conda install scikit-learn=0.24.2
 conda install seaborn=0.11.2

And, for running notebooks with no issue in python 3.9:
conda install -c conda-forge jupyterlab=3.1.8

Hope this helps! Will update when everything is tested and changes are merged with the master branch

**Comment by ajwlab** [comment]
Thank you! I'll try it out soon.

**Comment by ajwlab** [comment]
The application launches and the antibody comparisons work normally now after following the above instruction, however the application cannot be closed without hanging and then being forcequitted, and then the python kernel needs to restart before becoming usable again to run the program after that. 

It may be an issue just on my end though, I'm using spyder 5 with python 3.9.6 and all the above dependencies installed.

**Comment by ctboughter** [comment]
After a bit more testing, it seems that the combination of python 3.9.6/kivy 2.0.0/spyder 5 on my machine is incredibly unhappy (hangup issue/forcequitting that you discussed). If you're launching Spyder from Anaconda Navigator, I might recommend trying to launch Qt Console instead. The GUI appears to be more well behaved when executing "run aims.py" from this console. All of my code testing is done directly in the macOS terminal.

Given the most recent merged branch, which should remedy the issues with python 3.9, I'll close this issue now. Thanks again for bringing it up! The readme will now point users wishing to use python 3.9 to this issue.
